module.exports.defaultProfilePics = [
  { initial: "A", fileName: "TDfyr6Q.png" },
  { initial: "B", fileName: "m1m6DA9.png" },
  { initial: "C", fileName: "1sZUdsJ.png" },
  { initial: "D", fileName: "hB1M5qF.png" },
  { initial: "E", fileName: "MqArNrh.png" },
  { initial: "F", fileName: "R187ERG.png" },
  { initial: "G", fileName: "TaEzGdi.png" },
  { initial: "H", fileName: "nsknmNB.png" },
  { initial: "I", fileName: "faiEWE8.png" },
  { initial: "J", fileName: "zTjLmFU.png" },
  { initial: "K", fileName: "8Da2hAg.png" },
  { initial: "L", fileName: "wOc60mZ.png" },
  { initial: "M", fileName: "qeKvGey.png" },
  { initial: "N", fileName: "nzO8AHd.png" },
  { initial: "O", fileName: "DDMwgJT.png" },
  { initial: "P", fileName: "ISH6Oja.png" },
  { initial: "Q", fileName: "m9jnKQA.png" },
  { initial: "R", fileName: "QbgdoSj.png" },
  { initial: "S", fileName: "ePgSLGr.png" },
  { initial: "T", fileName: "7TnCxUs.png" },
  { initial: "U", fileName: "iabqSOe.png" },
  { initial: "V", fileName: "jZfaqv8.png" },
  { initial: "W", fileName: "y9UzOu6.png" },
  { initial: "X", fileName: "8KlO4q6.png" },
  { initial: "Y", fileName: "ZYk3LVP.png" },
  { initial: "Z", fileName: "ytAinIG.png" },
];
